server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 

jwt:    
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

      
      # MinIO对象存储相关配置
minio:
  endpoint: http://101.132.41.44:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
      
tenentcos:
   SecretId: AKIDtfFclgNp20kGYcR2PWQ7bsvlNmxwhGgu
   SecretKey: 5xc3GF1Zu1uZ0CAvSlrjNnzxiGbhaGiw
   endpoint: https://fu-1302032721.cos.ap-shanghai.myqcloud.com/
   bucketName: fu-1302032721
  