tenentcos:
   SecretId: AKIDtfFclgNp20kGYcR2PWQ7bsvlNmxwhGgu
   SecretKey: 5xc3GF1Zu1uZ0CAvSlrjNnzxiGbhaGiw
   endpoint: https://fu-1302032721.cos.ap-shanghai.myqcloud.com/
   bucketName: fu-1302032721